[features]
seeds = false
[programs.devnet]
# [programs.localnet]
sc_luxury_brand = "4XT394t9UT1VC56MzDgFN2nqdNTxLTSzZQVwCeoQkUSj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "/Users/lelong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
